//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computer_Shop_Management_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public int Category_Id { get; set; }
        public string Category_Name { get; set; }
        public string Category_Status { get; set; }
    }
}
