//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computer_Shop_Management_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Orders_Id { get; set; }
        public System.DateTime Order_Date { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Number { get; set; }
        public int Total_Amout { get; set; }
        public int Paid_Amout { get; set; }
        public int Due_Amout { get; set; }
        public int Discount { get; set; }
        public int Grand_Total { get; set; }
        public string Pament_Status { get; set; }
    }
}
