//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computer_Shop_Management_System.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Product_Id { get; set; }
        public string Product_Name { get; set; }
        public byte[] Product_Image { get; set; }
        public int Product_Rate { get; set; }
        public int Product_Quantity { get; set; }
        public string Product_Brand { get; set; }
        public string Product_Category { get; set; }
        public string Product_Stastus { get; set; }
    }
}
